# Dependencies
markdown:         redcarpet
pygments:      	  true

# Permalinks
#permalink:	  pretty
permalink:        /blog/:categories/:year/:month/:day/:title/

# Setup
title:            TBurette
tagline:          Dev Blog
url:              http://tburette.github.io
paginate:         1
paginate_path: 	  "blog/page:num"
baseurl:	  /
author:
  name:           Thomas Burette
  url:            https://github.com/tburette

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/tburette/tburette.github.io
