# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
#permalink:	  pretty
permalink:        /blog/:categories/:year/:month/:day/:title/

# Setup
title:            Thomas Burette
tagline:          Dev Blog
url:              http://tburette.github.io
paginate:         1
paginate_path: 	  "blog/page:num"
baseurl:	  
user_title:       Software Developer 
author:
  name:           Thomas Burette
  url:            https://github.com/tburette

plugins:
- jekyll-paginate

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/tburette/tburette.github.io
