# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            TBurette
tagline:          Dev Blog
url:              http://tburette.github.io/
paginate:         1

author:
  name:           Thomas Burette
  url:            https://github.com/tburette
  email:          burettethomas@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/tburette/tburette.github.io
